name: Code Quality Checks
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install black flake8
      - name: Check formatting with Black
        run: black --check .
      - name: Lint with Flake8
        run: flake8 .